### ISSUE TITLE
[ServiceProvider registration] Servise Provider was created without creation of Institution

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2216] opened 2023-08-23 10:29 UTC
**Environment:** 
Windows 11, 64 bit
Chrome 115.0.5790.171

**Reproducible:** Sometimes (once)

**Preconditions**
Go to https://oos.dmytrominochkin.cloud/#/
**Steps to reproduce**
1. Click on "Увійти/Зареєструватися" button at top right corner of Home page 
2. Go on "Зареєструватися" hiperlink
3. Select "Надавач послуг" tab
4. Fill in all mandatory fields 
5. Click on "Зареєструватися" button
6. Click on "Увійти" button on "Підтвердити електронну пошту" pop-up.
7. Scroll down on  the "Реєстрація нового закладу" page and click on "Скасувати" button.
8. Choose "Підтвердити" button

**Actual result**
The Servise Provider remained in the personal account with access to all tabs. The "Інформація про заклад" tab remained empty without the possibility to add a new institution and workshop

**Expected result**
Service Provider can not create personal account without creation of Institution

**User story and test case links**
[User story] [#312 GitHub](https://github.com/ita-social-projects/OoS-Backend/issues/312)

**Labels to be added**
"Bug", Priority ("Low"), Severity ("Medium"), Type ("Functional")

**Comment by doliinyk** [comment] 2023-12-23 15:54
At the moment provider can access links like workshops, rules, or the main page, but none of the provider tabs are displayed.
Can't reproduce by using UI only, but is accessed through URL, so still has to be fixed

**Comment by doliinyk** [comment] 2024-01-11 12:32
Fixed in #2334

**Closed as completed** 2024-02-26 11:20 UTC
Labels: bug:fixed, bug, validated
