### ISSUE TITLE
[Service Provider,Workshops] The number of students  on the workshop card is  displayed incorrectly

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2277] opened 2023-10-09 08:03 UTC
**Environment:** Windows 11, 64 bit
Chrome 117.0.5938.89
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/#/.
2. Log in as a Service Provider (e.g."Email" = 'SProvider@gmail.com', "password" = 'G23juhd!o')
3. SP has at least one workshop, credentials.
4. Workshop doesn't have any participants.

**Steps to reproduce**
1. Click on arrow or Last name at top right corner of the page
2. Select 'Мої гуртки' line from the drop-down list

**Actual result**
Total participants are displayed incorrectly on the workshop card:
On cards:
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/5b9b2bf3-5de3-4e78-998a-57c8164af3ab)
On "Заявки" tab:
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/d1c20031-41f1-4924-8bc4-1566b5298e2c)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/e8900ca1-ba8a-4da3-9bba-a625041d47ff)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/581d094f-a5a6-41c2-ae3c-869704d5f654)

**Expected result**
The number of students  on the workshop card is the same as number of aplications with status "Зараховано" or "Навчається 1-11 років".
**User story and test case links**

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("High"), Type ("Functional")

**Comment by doliinyk** [comment] 2023-12-23 16:25
Can't reproduce, might be fixed

**Comment by doliinyk** [comment] 2024-01-23 09:15
May be fixed in https://github.com/ita-social-projects/OoS-Backend/pull/1347

**Closed as completed** 2024-01-25 01:13 UTC
Labels: bug:fixed, backend, bug, validated
